### ISSUE TITLE
Login Actions

### ISSUE THREAD

**Issue by JTrembl1** [infinitered/ignite-example-login#5]
Sagas/LoginSagas.js

import LoginActions from '../Redux/LoginRedux'

I don't understand where LoginActions come from, or are used.

**Comment by wisn** [comment]
@JTrembl1 Read [this one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) first.

**Comment by exced** [comment]
Take a look at [redux-sauce](https://github.com/infinitered/reduxsauce), it's a tool to easily build Redux stuff. LoginActions contains the actions creators built by redux-sauce.
